using CSVOracle.Data.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace CSVOracle.Server.Dtos
{
	public class ChatDto
	{
		public int Id { get; set; }
		public string Name { get; set; } = null!;
		public string? UserView { get; set; }
		public List<string> Messages { get; set; } = null!;
		public string CurrentDatasetKnowledgeJson { get; set; } = null!;

		/// <summary>
		/// Creates a <see cref="ChatDto"/> instance from a given <see cref="Chat"/> entity.
		/// </summary>
		/// <param name="chat">The chat entity to map from.</param>
		/// <returns>A new <see cref="ChatDto"/> instance.</returns>
		public static ChatDto From(Chat chat)
		{
			var chatMessages = ChatHistory.FromChatHistoryJson(chat.ChatHistoryJson);
			List<string> messages = chatMessages.Select(m => string.Join("\n\n", m.Blocks.Select(b => b.Text))).ToList();

			return new ChatDto
			{
				Id = chat.Id,
				Name = chat.Name,
				UserView = chat.UserView,
				Messages = messages,
				CurrentDatasetKnowledgeJson = chat.CurrentDatasetKnowledgeJson
			};
		}

		public enum ChatMessageRole
		{
			/// <summary>The message was sent by the user.</summary>
			User,

			/// <summary>The message was generated by the assistant.</summary>
			Assistant
		}

		public class Block
		{
			public string BlockType { get; set; } = null!;
			public string Text { get; set; } = null!;
		}

		public class ChatMessage
		{
			public string Role { get; set; } = null!; // "user" or "assistant"
			public Dictionary<string, object> AdditionalKwargs { get; set; } = null!;
			public List<Block> Blocks { get; set; } = null!;

			[JsonConstructor]
			public ChatMessage()
			{
				// Empty
			}

			public ChatMessage(ChatMessageRole role, string text)
			{
				Role = GetRoleString(role);
				AdditionalKwargs = new Dictionary<string, object>();
				Blocks = new List<Block>
				{
					new Block{
						BlockType = "text",
						Text = text
					}
				};
			}

			private string GetRoleString(ChatMessageRole role) =>
				role switch
				{
					ChatMessageRole.User => "user",
					ChatMessageRole.Assistant => "assistant",
					_ => throw new Exception($"Unknown {nameof(ChatMessageRole)} value.")
				};
		}

		public static class ChatHistory
		{
			private static readonly JsonSerializerSettings defaultSettings = new()
			{
				ContractResolver = new DefaultContractResolver
				{
					NamingStrategy = new SnakeCaseNamingStrategy()
				}
			};

			/// <summary>
			/// Serializes a list of <see cref="ChatMessage"/> objects into a JSON string.
			/// </summary>
			/// <param name="chatMessages">The list of chat messages to serialize.</param>
			/// <returns>A JSON string representing the serialized chat history.</returns>
			public static string ToChatHistoryJson(List<ChatMessage> chatMessages)
			{
				var chatHistoryJson = JsonConvert.SerializeObject(chatMessages, defaultSettings);

				return chatHistoryJson;
			}

			/// <summary>
			/// Deserializes a JSON string into a list of <see cref="ChatMessage"/> objects.
			/// </summary>
			/// <param name="chatHistoryJson">The JSON string representing the chat history.</param>
			/// <returns>A list of <see cref="ChatMessage"/> objects.</returns>
			/// <exception cref="Exception">Thrown if the JSON cannot be deserialized into a valid chat history.</exception>
			public static List<ChatMessage> FromChatHistoryJson(string chatHistoryJson)
			{
				var chatHistory = JsonConvert.DeserializeObject<List<ChatMessage>>(chatHistoryJson, defaultSettings);
				if (chatHistory is null)
				{
					throw new Exception("Invalid chat history JSON, cannot deserialize.");
				}

				return chatHistory;
			}
		}
	}
}
